### ISSUE TITLE
Tip Position

### ISSUE THREAD

**Issue by babulpatel1309** [jayrambhia/Tooltip#2]
Is there any method where i can adjust a tip position ? Like if my button is on right corner up side then Tip start point ll generate on Right edge of the popup.??? OR its auto managed?

**Comment by jayrambhia** [comment]
You can not adjust the tip position. It will always be at the center of that edge. You can provide the edge where you want it to be drawn via position.

If your button is at top right corner of the screen and you want to show the tooltip, you may show it on the left edge of bottom edge. Left edge would be ideal.

`.anchor(anchorView, Tooltip.LEFT)`
