### ISSUE TITLE
Cancel/remove tooltip when user touch on any parts of screen

### ISSUE THREAD

**Issue by GauravP123** [jayrambhia/Tooltip#3]
When tooltip is visible and user click on any other part of the screen say user click on button and tooltip is visible and then user click on different button is any way we can cancel or remove tooltip  instead of waiting for tooltip duration time to get over

**Comment by jayrambhia** [comment]
You may use `.cancelable(true)` and it will automatically remove the tooltip if the user clicks anywhere on the screen except the tooltip.
